import re
import json
from typing import List, Union, Optional
import logging

from giskard.rag.metrics.base import Metric
from giskard.rag.base import AgentAnswer
from ...llm.client import ChatMessage, LLMClient, get_default_client
from ..question_generators.utils import parse_json_output

logger = logging.getLogger(__name__)

NUMERICAL_EXTRACTION_SYSTEM_PROMPT = """You are an expert in numerical extraction. Your task is to extract all numerical values from a given text and normalize them to floats.

Rules:
1. Extract integers, decimals, and scientific notation.
2. Convert percentages to their decimal form (e.g., "12.5%" -> 0.125, "100%" -> 1.0).
3. Convert textual numbers to floats (e.g., "one million" -> 1000000.0, "half" -> 0.5).
4. Ignore currency symbols but keep the value.
5. Return the result as a JSON object with a single key "numbers" containing a list of floats.

Example Input: "The company reported 50% growth, reaching 1.5 million revenue."
Example Output: {"numbers": [0.5, 50.0, 1500000.0]} 
(Note: For percentages, it is often ambiguous if 50% means 0.5 or 50.0 in context. Extract BOTH if unsure, or prefer the raw number 50.0 if the context implies a statistic, but 0.5 if it implies a ratio. For this specific tool, prefer extracting what is literally in the text as a number. So "50%" -> 50.0).
WAIT, let's refine: To be safe against "0.5" vs "50%", specific logic in the code handles equivalence. Just extract the raw value associated. "50%" -> 50.0.
"""

class NumericalFaithfulnessMetric(Metric):
    """
    Measures the faithfulness of numerical values in the agent's answer with respect to the context.
    It checks if every number mentioned in the answer is also present in the context (within a tolerance).
    """
    def __init__(self, name: str = "numerical_faithfulness", tolerance: float = 0.01, use_llm: bool = True, llm_client: LLMClient = None):
        self.name = name
        self.tolerance = tolerance
        self.use_llm = use_llm
        self._llm_client = llm_client

    def _extract_numbers_regex(self, text: str) -> List[float]:
        """
        Extracts all numbers from a string using Regex.
        """
        # Heuristic cleanup: remove commas from numbers like 1,000
        text_clean = text.replace(",", "")
        
        # Regex for floats
        matches = re.findall(r'-?\d+\.?\d*(?:[eE][-+]?\d+)?', text_clean)
        
        numbers = []
        for m in matches:
            if not m: continue
            if m in ['-', '.']: continue # Skip lone signs
            try:
                numbers.append(float(m))
            except ValueError:
                pass
        return numbers

    def _extract_numbers_llm(self, text: str) -> List[float]:
        """
        Extracts numbers using an LLM.
        """
        llm_client = self._llm_client or get_default_client()
        try:
            out = llm_client.complete(
                messages=[
                    ChatMessage(role="system", content=NUMERICAL_EXTRACTION_SYSTEM_PROMPT),
                    ChatMessage(role="user", content=f"Text: {text}"),
                ],
                temperature=0,
                format="json_object",
            )
            json_output = parse_json_output(out.content, llm_client=llm_client, keys=["numbers"])
            return [float(x) for x in json_output.get("numbers", [])]
        except Exception as err:
            logger.warning(f"LLM extraction failed: {err}. Falling back to Regex.")
            return []

    def extract_numbers(self, text: str) -> List[float]:
        """
        Extracts numbers using the configured method(s).
        """
        numbers = set(self._extract_numbers_regex(text))
        
        if self.use_llm:
            llm_numbers = self._extract_numbers_llm(text)
            numbers.update(llm_numbers)
            
        return list(numbers)

    """
    Computes numerical faithfulness score by checking if numbers in the agent answer are present in the context.

    Parameters
    ----------
    question_sample : dict
        Sample dictionary containing the question and reference context (optional).
    answer : AgentAnswer
        The answer generated by the agent, containing the message and retrieved documents.

    Returns
    -------
    dict
        Dictionary with the score (0.0 to 1.0) and optionally a reason for failure.
    """
    def __call__(self, question_sample: dict, answer: AgentAnswer) -> dict:
        context_text = ""
        if answer.documents:
            context_text = " ".join(answer.documents)
        elif "reference_context" in question_sample:
             context_text = question_sample["reference_context"]
        
        if not context_text:
            return {self.name: 1.0}

        answer_numbers = self.extract_numbers(answer.message)
        context_numbers = self.extract_numbers(context_text)

        failed_numbers = []
        
        for num in answer_numbers:
            # Check if num is close to ANY number in context
            found = False
            for c_num in context_numbers:
                # Standard tolerance check
                if abs(num - c_num) <= self.tolerance * max(abs(num), abs(c_num)) + 1e-9:
                     found = True
                     break
                
                # Percentage / Factor of 100 check (e.g. 0.125 vs 12.5)
                # Ideally, if the text says "12.5%", regex might extract 12.5. 
                # If context says "0.125", we want them to match? 
                # Or if context says "12.5%" (extracted 12.5) and answer says "0.125" (extracted 0.125).
                # Let's add a loose check for factor of 100 if one looks like a ratio and other a percent.
                if abs(num * 100 - c_num) <= self.tolerance * max(abs(num * 100), abs(c_num)) + 1e-9:
                    found = True
                    break
                if abs(num - c_num * 100) <= self.tolerance * max(abs(num), abs(c_num * 100)) + 1e-9:
                    found = True
                    break

            if not found:
                failed_numbers.append(num)
        
        if not answer_numbers:
             score = 1.0
        else:
             score = 1.0 - (len(failed_numbers) / len(answer_numbers))

        result = {self.name: score}
        if failed_numbers:
            result[f"{self.name}_reason"] = f"The following numbers in the answer were not found in the context: {failed_numbers}"
        
        return result

numerical_faithfulness_metric = NumericalFaithfulnessMetric()
