[project]
name = "giskard-checks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jsonpath-ng>=1.7.0,<2",
    "pydantic>=2.11.7,<3",
    "counterpoint>=0.2.3,<1",
    "jinja2>=3.1.6,<4",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"
pythonpath = ["src"]

[tool.ruff.lint]
select = ["E", "W", "I", "F401"]
ignore = ["E501"]

[tool.pyright]
failOnWarnings = false
typeCheckingMode = "recommended"
reportImportCycles = "warning"

[build-system]
requires = ["hatchling>=1.25.0"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest==8.4.2",
    "pytest-asyncio==1.2.0",
]

[tool.hatch.build.targets.wheel]
packages = ["src/giskard"]

[tool.hatch.build.targets.sdist]
include = [
  "src/giskard/checks",
  "README.md",
  "pyproject.toml",
]

[tool.uv.sources]
counterpoint = { git = "https://github.com/Giskard-AI/counterpoint.git", tag = "v0.2.3" }
