[project]
name = "giskard-checks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "counterpoint>=0.1.2",
    "jsonpath-ng>=1.7.0",
    "pydantic~=2.11.7",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"
pythonpath = ["src"]

[tool.ruff.lint]
select = ["E", "W", "I"]
ignore = ["E501"]

[tool.pyright]
failOnWarnings = false
typeCheckingMode = "recommended"
reportImportCycles = "warning"

[build-system]
requires = ["hatchling>=1.25.0"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "pytest-asyncio>=1.1.0",
]

[tool.hatch.build.targets.wheel]
packages = ["src/giskard_checks"]

[tool.hatch.build.targets.sdist]
include = [
  "src/giskard_checks",
  "README.md",
  "pyproject.toml",
]

[tool.uv.sources]
counterpoint = { git = "ssh://git@github.com/Giskard-AI/counterpoint.git", tag="v0.1.2" }
