name: Release Giskard Core
on:
  push:
    branches: [main]
    paths: ["libs/giskard-core/pyproject.toml"] # Only triggers if pyproject.toml changes (potential version bump)

jobs:
  call-release:
    uses: ./.github/workflows/_release_template.yml
    with:
      package_name: "giskard-core"
    secrets: inherit
